import "@/styles/globals.scss";
import type { AppProps } from "next/app";
import Head from "next/head";
import { RecoilRoot } from "recoil";
import { AnimatePresence } from "framer-motion";
import { WindowSizeContext } from "@/components/shared";
import Layout from "@/components/Layout";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <RecoilRoot>
      <Head>
        <title>taese0ng_portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WindowSizeContext>
        <AnimatePresence mode="wait" initial={false}>
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </AnimatePresence>
      </WindowSizeContext>
    </RecoilRoot>
  );
}
