import "@/styles/globals.scss";
import type { AppProps } from "next/app";
import Head from "next/head";
import { RecoilRoot } from "recoil";
import { AnimatePresence } from "framer-motion";
import { WindowSizeContext } from "@/components/shared";
import { useGetWindow } from "@/hooks";
import { useRouter } from "next/router";
import { Fragment, useEffect } from "react";
import Layout from "@/components/Mobile/Layout";

function MyApp({ Component, pageProps }: AppProps) {
  const { isMobile } = useGetWindow();
  const router = useRouter();

  useEffect(() => {
    const pathname = isMobile ? "/mobile" : "/desktop";

    router.replace(pathname);
  }, [isMobile]);

  return (
    <Fragment>
      {isMobile ? (
        <Layout>
          <Component {...pageProps} />
        </Layout>
      ) : (
        <Component {...pageProps} />
      )}
    </Fragment>
  );
}

export default function App(appProps: AppProps) {
  return (
    <RecoilRoot>
      <Head>
        <title>taese0ng_portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WindowSizeContext>
        <AnimatePresence mode="wait" initial={false}>
          <MyApp {...appProps} />
        </AnimatePresence>
      </WindowSizeContext>
    </RecoilRoot>
  );
}
